### ISSUE TITLE
Turn "doc" repo into github pages repo

### ISSUE THREAD

**Issue by Emanuel-Allely** [Luos-io/doc#11]
To turn "doc" repo into github pages repo we need to call it "luos-io.github.io" as it is mentionned here : https://guides.github.com/features/pages/. And if everything works well, the url luos-io.github.io will be automatically link to this repo, so to our doc.

Next step is to think about embed this url with our domain name. Something like doc.luos.io.

**Comment by Simonbdy** [comment]
This will be done at the same time we push the new doc to master if it's ok

**Comment by Simonbdy** [comment]
@Emanuel-Allely, does this issue still need to be open, now that the CNAME file works for redirection?
